DROP DATABASE IF EXISTS ssmtest;
CREATE DATABASE ssmtest;
USE ssmtest;
CREATE TABLE test(
	id INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(32) DEFAULT NULL,
	PRIMARY KEY(id) 
) CHARACTER SET = utf8;